name: Create Cluster

on:
  workflow_dispatch:
    
jobs:
  CI:
    runs-on: ubuntu-latest
    
    steps:
    
    - uses: actions/checkout@v1
    
    - name: yq setup
      run: | 
        sudo wget -O /usr/local/bin/yq https://github.com/mikefarah/yq/releases/download/3.3.0/yq_linux_amd64
        sudo chmod +x /usr/local/bin/yq
    
    - name: Replace
      run: |
        cat edit.yaml
        yq w -i edit.yaml "spec.template.spec.containers[0].args[+]" "OUT_NEW_VALUE"
        yq w -i edit.yaml "spec.template.spec.containers[0].args[+]" "SECOND_NEW_VALUE"
        yq w -i edit.yaml "spec.template.spec.containers[0].args[+]" "THIRD_NEW_VALUE"
        cat edit.yaml

    
