name: Create Cluster

on:
  workflow_dispatch:
    
jobs:
  CI:
    runs-on: ubuntu-latest
    
    steps:
    
    - uses: actions/checkout@v1
    
    - name: yq - portable yaml processor
      uses: mikefarah/yq@3.4.0
    
    - name: Replace
      run: |
        cat edit.yaml
        yq w -i -d 1 edit.yaml spec.template.spec.containers.image OUT_NEW_VALUE
        cat edit.yaml

    
